### ISSUE TITLE
Transcript support for all SRT mimetypes

### ISSUE THREAD

**Issue by Marzal** [amugofjava/anytime_podcast_player#102]
**Describe the bug**
I think that the code doesn't catch al the possible mime-types for SRT transcripts (or at least I can't found it):

https://github.com/amugofjava/anytime_podcast_player/blob/b4a154c529274612cec01b18d59a9cfd88ca6ea3/lib/entities/transcript.dart#L8

https://github.com/amugofjava/anytime_podcast_player/blob/master/lib/ui/podcast/transcript_view.dart

These all the types that I've found podcast using for SRT:
- application/x-subrip
- application/srt
- text/srt

**To Reproduce**
1. Add this feed:  [Mixxio'](http://podcast.mixx.io/diario.rss)
2. Click on 'Play' on last episode
3. Scroll down to 'Transcripts'

**Expected behavior**
Subtitles are shown as on [KDE Express](https://kdeexpress.gitlab.io/feed)

**Screenshots**
![imagen](https://github.com/amugofjava/anytime_podcast_player/assets/2069735/6b5aa5ac-6642-483f-82d1-cc51d2364f34)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: Android 13

**Additional context**
Mixxio:
- `<podcast:transcript type="plain/txt" url="https://cuonda.com/mixxio/la-temporada-otono-invierno/transcription"/>`

- `<podcast:transcript type="application/x-subrip" rel="captions" url="https://cuonda.com/mixxio/la-temporada-otono-invierno/subtitles"/>`

KDE Express:
- `<podcast:transcript language="es" rel="captions" url="https://op3.dev/e,pg=a9a56b87-575a-5f6f-9636-cdf7b73e6230/archive.org/download/19-kde-express-parati/19-KDE_Express-Parati.vtt" type="text/vtt"/>`

- `<podcast:transcript language="es" rel="captions" url="https://op3.dev/e,pg=a9a56b87-575a-5f6f-9636-cdf7b73e6230/archive.org/download/19-kde-express-parati/19-KDE_Express-Parati.asr.srt" type="application/x-subrip"/>`

- `<podcast:transcript language="es" rel="captions" url="https://op3.dev/e,pg=a9a56b87-575a-5f6f-9636-cdf7b73e6230/archive.org/download/19-kde-express-parati/19-KDE_Express-Parati.asr.srt" type="application/srt"/>`

- `<podcast:transcript language="es" rel="captions" url="https://op3.dev/e,pg=a9a56b87-575a-5f6f-9636-cdf7b73e6230/archive.org/download/19-kde-express-parati/19-KDE_Express-Parati.asr.srt" type="text/srt"/>`

PD: Thanks for supporting the Podcasting 2.0 community with FLOSS

**Comment by amugofjava** [comment]
Hi @Marzal,

Thank you for the bug report. Anytime doesn't support the `text/srt` mime type so I'll look to get that added. Anytime does support `application/x-subrip` which the Mixxio podcast is using. I've tried listening to the latest episode on a few devices and it's working for me, so I wonder if there is some other issue that's happening here.

<img src="https://github.com/amugofjava/anytime_podcast_player/assets/5526902/00142f18-e86a-43c7-b7fb-441a5a1fa286" width="360">


Please could you let me know the region and language settings you have on your phone in case it's something to do with that.

Thanks.

**Comment by Marzal** [comment]
Sorry my bad, I was using a similar feed (premium without ads) and it seems that the public feed has the transcript tags in all the episodes but the premium one only in a few. I would contact the podcaster as is not a problem in Anytime, sorry for the trouble.

**Comment by amugofjava** [comment]
No problem @Marzal - I can still add support for `text/srt`. Thanks for trying out Anytime.
