### ISSUE TITLE
Notification shade can be swiped away during playback on Android 11 and above

### ISSUE THREAD

**Issue by amugofjava** [amugofjava/anytime_podcast_player#109]
**Describe the bug**
The notification control allows users to play, pause, forward and rewind playback from the notification shade. When in a paused state, it is also possible to swipe the notification away to stop playback; however, on Android 11 and above it is possible to swipe the notification away whilst an episode is playing. This removes the notification but does not stop playback living it out of sync. 

**To Reproduce**
1. On a Device running Android 11 or above.
2. Start playback of an episode.
3. Pull down the notification shade.
4. Swipe the notification away.

**Expected behavior**
Playback should either stop when swiped away, or the same behaviour - as observed on Android 10 and below - should be followed making it only possible to swipe away the notification when in a paused state.

**Screenshots**

[notification-bug.webm](https://github.com/amugofjava/anytime_podcast_player/assets/5526902/7e59a465-9786-40f5-8cdf-b952f929117c)

**Smartphone (please complete the following information):**
 - Device: Google Nexus X, Pixel 2.
 - OS: Android 8.1.0, 11.

**Comment by srihariash999** [comment]
I think this is the default android behaviour, even if you swipe off the notification from the drawer, the media keeps playing and you can access the notification by swiping down again the notification drawer (full extended notifications drawer) and you will find the media playback controls there.



https://github.com/user-attachments/assets/9dc4921b-50f3-4de2-8a6b-1d9259c7b55a

**Comment by srihariash999** [comment]
Ref: https://github.com/ryanheise/audio_service/issues/1064
