### ISSUE TITLE
Add option to automatically remove downloaded episodes once played

### ISSUE THREAD

**Issue by amugofjava** [amugofjava/anytime_podcast_player#112]
**Is your feature request related to a problem? Please describe.**
Once a downloaded episode has been fully played, it remains in the Downloads section until you manually remove it. Each episode has to be removed one at a time which can be frustrating.

**Describe the solution you'd like**
A new option 'Remove downloaded episodes once played' should be added to the settings page in the Episodes section. When toggled on, upon reaching the end of playback of an episode which is downloaded to the user's device, it should be deleted.

**Comment by mrkrash** [comment]
Hello @amugofjava,

can I develop this feature?

**Comment by amugofjava** [comment]
Hi @mrkrash,

Sure, I'll assign the issue to you. Thank you.
