### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by D4RKW1NT3R** [amugofjava/anytime_podcast_player#113]
**Is your feature request related to a problem? Please describe.**
Although this may not affect most people, I would like it if this app was added to F-Droid.

**Additional context**
This would bring in more people from the Foss community to download the app and could do nothing but good.

**Comment by amugofjava** [comment]
Hi,

I am still looking into this, but will have to pause for a while. As F-Droid builds the application from source I need to find a way to handle the PodcastIndex API keys that are required for searching without committing them to the source code.

**Comment by IzzySoft** [comment]
> a way to handle the PodcastIndex API keys that are required for searching without committing them to the source code.

The only way known to me there is to have those using your app requesting their own API keys and providing a field in the configuration so they can add it.

Meanwhile, mind to make your APK available e.g. as attachments to [releases](https://github.com/amugofjava/anytime_podcast_player/releases)? I could then check if they can be added to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) :wink:

**Comment by amugofjava** [comment]
Given that the keys are not very sensitive and could be extracted from the APK, I am considering following as AntennaPod do and just put the keys in a config file.

I will try to remember to add the APKs to releases @IzzySoft :)

**Comment by IzzySoft** [comment]
> I will try to remember to add the APKs to releases

That will be much appreciated! And even needed if you want to go "reproducible builds" (F-Droid would then distribute the APK you signed, as IzzyOnDroid does).

**Comment by IzzySoft** [comment]
PS: Please give me a ping once APKs are there. Would also help you with a "pre-scan" for how close you are to be ready for F-Droid.

**Comment by amugofjava** [comment]
I have a working .yml file that builds successfully via `fdoid build`, but I am having issues testing the build - `fdroid publish` just fails. Making progress though!

**Comment by IzzySoft** [comment]
Well… `fdroid publish` is called to sync to your fdroid server on the net, i.e. to put APKs and indices to your public repository. Not sure if that's what you had in mind… As pointed out, providing the APK here at [releases](https://github.com/amugofjava/releases) would allow me to see if it can be added to the IzzyOnDroid repository – and go right ahead with that if the [IzzyOnDroid App Inclusion Criteria](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy) are met.

**Comment by amugofjava** [comment]
Hi @IzzySoft,

I have created a new release - v1.3.9 - and added the apk. I am currently working to get Anytime on F-Droid. So far, I can do a successful `fdroid build uk.mu.amugofjava.anytime`; however, the F-Droid pipeline is currently failing on build so I am looking in to this.

**Comment by amugofjava** [comment]
Hi @D4RKW1NT3R & @IzzySoft,

Anytime is now available on F-Droid. You can find it at: https://f-droid.org/en/packages/uk.me.amugofjava.anytime

Thanks.

**Comment by IzzySoft** [comment]
Apologies for lack of response, I was on vacation… Congrats to your listing! All solved then I guess?

**Comment by amugofjava** [comment]
Yes, took a little back-and-forth, but the F-Droid team were very helpful and it's all working.

**Comment by Poussinou** [comment]
You can add a F-Droid button to get the app

`[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
     alt="Get it on F-Droid"
     height="80">](https://f-droid.org/packages/uk.me.amugofjava.anytime/)`
