### ISSUE TITLE
Change orientation from the first to the last and vice versa!

### ISSUE THREAD

**Issue by RyanOrigens** [amugofjava/anytime_podcast_player#117]
It would be nice if it had a feature to enable me to change the orientation of the displayed episodes from the first to the last and vice-versa!

I generally listen to episodes from the first to the last posted rather than from the last to the first, and it is quite annoying having to scroll down until the bottom of the screen every time i need to get there, mainly when it has a bunch of episodes.

**Comment by amugofjava** [comment]
Hi @RyanOrigens,

This feature is planned for the near future. I have pushed a new release to Apple Test Flight and Google Play Beta (awaiting review) that adds an episode filter option. The next step for the episode page is to add sorting.

**Comment by amugofjava** [comment]
Closing this issue as this has been released in v1.3.8.
