### ISSUE TITLE
Remind pre-loaded episodes even when it was removed from the RSS file!

### ISSUE THREAD

**Issue by RyanOrigens** [amugofjava/anytime_podcast_player#118]
The problem I'm encountering is with a podcast that I enjoy. It has dozens of episodes, but they periodically remove some from the RSS feed. Since I prefer to listen from the first episode to the last, the episode I intend to listen to often gets deleted before I can access it.

If a podcast app could retain pre-loaded episodes even after they're removed from the RSS feed, it would solve this issue for me. One example of an app that employs this approach is TSACDOP, which is a FOSS app. You could look into the code to replicate its functionalities.

By PRE-LOADED Episodes i don't mean DOWNLOADED ONES, i mean episodes that the link to the episode was already fetched!

**Comment by amugofjava** [comment]
Hi @RyanOrigens,

Anytime does keep in sync with the RSS feed, so if episodes are removed from the feed Anytime will also remove them from the list - except if the episode is already downloaded.

The problem with keeping episodes that are no longer in the feed, is that Anytime cannot tell if the episode MP3 file still exists and has simply been removed from the RSS, or if the MP3 has been removed as well until you attempt to play it. This would make for a poor user experience if Anytime failed to play episodes that it listed.

I will take a look at Tsacdop, although it does not look like it is still maintained.

**Comment by amugofjava** [comment]
Unfortunately, Tsacdop is no longer maintained. Giving this more thought, I still feel that holding on to episodes that are no longer in the feed and no longer downloaded who result in a poor experience. One reason I introduced the RSS episode sync early on was to ensure that it was less likely to end up with dead episodes.

I think keeping old episodes downloaded is the way to go with this. I am considering filters to the download section. In this way, you could make episodes that you wish to keep, but not appear by default in the Downloads tab as favourite, or archived or something like that.
