### ISSUE TITLE
Podcast description text block is not anchored to its parent

### ISSUE THREAD

**Issue by amugofjava** [amugofjava/anytime_podcast_player#124]
**Describe the bug**
The podcast details page shows the podcast description, which can be expanded or collapsed if necessary; however, the text block is not anchored to the top of its parent, so the margin at the top of the text block can vary between podcasts. This is particularly noticeable at lower resolutions.

**To Reproduce**
1. Open a podcast.
2. Open a second, third etc and see the margin at the top of the text block change.

**Expected behavior**
The text block should be anchored to the top of its parent to keep the margin and padding consistent.

**Screenshots**
<p align="left">
  <img src="https://github.com/amugofjava/anytime_podcast_player/assets/5526902/1d3b1ad3-43d8-4345-92d6-4646f7ed9c3e" width="350" title="Example image 1">
  <img src="https://github.com/amugofjava/anytime_podcast_player/assets/5526902/2e8cf24a-8f25-4a53-b344-277492aeeec7" width="350" alt="Example image 2">
</p>

**Comment by filip-alexandrov** [comment]
As I understand, the margin above the description text is part of the HTML renderer itself. Most show descriptions are in plain text (as opposed to episode descriptions). HTML and plain text are prestyled differently. 

![2 5 Admins - plain](https://github.com/amugofjava/anytime_podcast_player/assets/79532720/7438bcff-5fc4-40f8-aaa2-bc85486f6a92)

![Add to playlist - html](https://github.com/amugofjava/anytime_podcast_player/assets/79532720/bc0909dc-043a-4df3-a5e7-8d4c3a8cf442)

Here "Add to playlist" has wrapped its description inside <p> tag. There is added vertical margin to <p> tags by default. On the contrary, "2.5 Admins" has plain-text description and the absense of a <p> tag can be seen in the reduced margin above the text field.

Fixing this will require setting <p> tag margins to 0, but there can be other tags with default styling like <h1> title tags. I have rarely seen tags other than <p> in the show description. I will include a fix in #123
