### ISSUE TITLE
Search within given podcast

### ISSUE THREAD

**Issue by adrienneteicher** [amugofjava/anytime_podcast_player#131]
Sometimes I'm trying to find an older episode in a podcast going back years and endless scrolling can be exhausting.

It would be great if we could search for text within episode descriptions themselves.

Thanks!!

**Comment by amugofjava** [comment]
Hi @adrienneteicher,

Yes, I completely agree. Anytime needs this to make it easier to find episodes. 

Thanh you.

**Comment by adrienneteicher** [comment]
Sweet. Thanks!
Best,
Adrienne Teicher
adrienneteicher.com[https://www.adriennneteicher.com] | hyenaz.com[https://www.hyenaz.com]
Sent from my phone

6 Oct 2024 18:25:03 Ben Hills ***@***.***>:

**Comment by amugofjava** [comment]
Here is a rough implementation of how I think this would look & work. What do you think?


https://github.com/user-attachments/assets/0e82736a-fd83-4b8b-b1d6-0aaa33268aa4

**Comment by amugofjava** [comment]
This has been added in v1.3.10 which is currently available on the Google & Apple stores. Will follow up with F-Droid and amazon shortly.

**Comment by adrienneteicher** [comment]
Nice one! Thank you!!
