### ISSUE TITLE
just_audio upgrade issues

### ISSUE THREAD

**Issue by vnl** [amugofjava/anytime_podcast_player#2]
**just_audio causes issues after upgrading**
A direct build without any changes could not complete with several build errors stating ios build version differences. So I went ahead and upgraded all the individual packages. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Updated the pubspec yaml with the latest versions of the packages used (versions shown below)
2. Compile errors are shown within the 'mobile_audio_player.dart' file

**Expected behaviour**
Should have hopefully built with the latest packages. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1355466/104119622-74e69d80-5328-11eb-898f-0d07ef7ec139.png)
![image](https://user-images.githubusercontent.com/1355466/104119636-8d56b800-5328-11eb-95a8-1e99784809b8.png)

**Smartphone (please complete the following information):**
 - Device: Simulator (iPhone 12 Pro - iOS 14.3)
 - OS: iOS 14.3

**Additional context**
`environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_service: ^0.16.1
  cached_network_image: ^2.5.0
  connectivity: ^2.0.2
  cupertino_icons: ^0.1.2
  flutter_dialogs: ^1.1.0
  flutter_downloader: ^1.5.2
  flutter_launcher_icons: ^0.8.1
  flutter_spinkit: ^4.1.2+1
  html: ^0.14.0+4
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  just_audio: ^0.6.5
  liquid_pull_to_refresh: ^2.0.0
  logging: ^0.11.4
  mockito: ^4.1.3
  mp3_info: ^0.1.4
  package_info: ^0.4.3+2
  path_provider: ^1.6.27
  percent_indicator: ^2.1.9
  permission_handler: ^5.0.1+1
  podcast_search: ^0.3.7
  provider: ^4.3.2+3
  rxdart: ^0.25.0
  sembast: ^2.4.8+1
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2`

[Pastebin - initial build error](https://pastebin.com/9qwEmcZw)

**Comment by amugofjava** [comment]
Hi,

iOS support is still work in progress; however, I do have a set of changes - currently sat in the feature/ios branch - that produces a successful build for iOS (via CI). I will be merging these into master this week, but if you would like to check out the branch and let me know if it builds successfully for you that would be great.

The just_audio and audio_service packages are under very active development and there are a couple of breaking changes in recent releases: [0.6.0](https://pub.dev/packages/just_audio/changelog) in just_audio and [0.14.0](https://github.com/ryanheise/audio_service/wiki/Migration-Guide#0140) in audio_service. There are a number of dependencies that have become out of date whilst I have concentrated on stability improvements and bug fixes, but I intend to address these next.

**Comment by vnl** [comment]
Oooh, that branch was so close :) It builds and installs and then a run time error:

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
lib/main.dart:1
Xcode build done.                                           24.9s
Connecting to VM Service at ws://127.0.0.1:58521/UCph8vRw6vA=/ws
flutter: FINE: - 2021-01-10 17:31:10.487085: Chrome: transparentLight()
Lost connection to device.
Exited (sigterm)
```

**Comment by amugofjava** [comment]
Yes, I am finding the same issue. Frustratingly, it builds and installs but then looses connection to the device as the app starts. I will do some investigating.

**Comment by vnl** [comment]
Do you think this is because some plugins need user permissions and that is not set yet?

**Comment by vnl** [comment]
If it helps, the crash occurs in "mobile_download_service.dart" line 40.
```
/// An implementation of a [DownloadService] that handles downloading
/// of episodes on mobile.
class MobileDownloadService extends DownloadService {
  static BehaviorSubject<DownloadProgress> downloadProgress = BehaviorSubject<DownloadProgress>();

  final log = Logger('MobileDownloadService');

  @override
  final Repository repository;
  final ReceivePort _port = ReceivePort();

  MobileDownloadService({@required this.repository}) : super(repository: repository) {
    _init();
  }
```

**Comment by amugofjava** [comment]
When re-creating some of the iOS files I missed adding support for the sqlite library required by flutter_downloader. I have pushed a fix to the iOS branch, so the app will now compile and run. iOS support is still very much work in progress whilst the app now runs it still does not work correctly. There is a little way to go until I can release a polished version of Anytime for iOS - but definitely it's getting there.

**Comment by vnl** [comment]
I noticed, I figured out the changes and was about to make a push only to realise you beat me to it :)

**Comment by amugofjava** [comment]
I'm not sure what is causing the error shown in your screenshot - it should work fine on Android - indeed I use in on Android daily. Is it not populating the discovery tab there?

**Comment by vnl** [comment]
yeah, discovery is not populating
I am not creating another issue yet, will restart the laptop in a while and then try again. and keep you posted. 
Any chance you will be merging the ios branch to master?

**Comment by amugofjava** [comment]
Yes, I'm happy the iOS changes does not break anything so I will merge to master later today.

**Comment by amugofjava** [comment]
I have merged the changes to master and deleted the feature/ios branch.
