### ISSUE TITLE
No HTTP user-agent makes it hard for podcasters

### ISSUE THREAD

**Issue by jamescridland** [amugofjava/anytime_podcast_player#21]
**Describe the bug**

This app does not seem to set an HTTP useragent for its audio player. This is bad, and means podcasters do not know what product is consuming their free content.

**To Reproduce**

Listen to a podcast. The podcast publisher gets this as an HTTP useragent:

`just_audio/0.2.0 (Linux;Android 6.0) ExoPlayerLib/2.12.2`

This is the player within this app. It should be something like

`Anytime/0.2.0 (Linux;Android 6.0) https://github.com/amugofjava/anytime_podcast_player`

**Expected behavior**
Send a correct HTTP useragent

**Screenshots**
None

**Smartphone (please complete the following information):**
I've no idea what smartphone this user is using, other than it appears to be running Android 6, so is very old.

**Additional context**

A full set of useragents are here: https://github.com/opawg/user-agents

I've spotted your app here: https://podnews.net/about/podcast-stats

**Comment by amugofjava** [comment]
Thanks @jamescridland for raising this bug. Have fixed it locally and will push an update as soon as possible. You should see a more appropriate user agent appear:

`Anytime/0.2.1 (phone;Android 10) https://github.com/amugofjava/anytime_podcast_player`

**Comment by amugofjava** [comment]
Issue resolved.
