### ISSUE TITLE
NowPlaying view rendered without chapters for a first time loaded podcast.

### ISSUE THREAD

**Issue by roeierez** [amugofjava/anytime_podcast_player#31]
When loading a podcast for the first time (one that has chapters) they are not showing in the now playing view.
I believe the reason is because the podcast is added to the stream before chapters are loaded: https://github.com/amugofjava/anytime_podcast_player/blob/master/lib/bloc/podcast/audio_bloc.dart#L101

The chapters are actually lazy loaded inside the mobile audio player service but the line above doesn't wait for it.
Adding wait will fix this issue but will create some flickering in the now playing UI and some "jump" in the tab selected index.

**Comment by amugofjava** [comment]
Hey @roeierez,

Yes, I have already fixed this locally. The NowPlaying form was only checking for chapters at the point of instantiation and so if they weren't loaded at that point the chapters tab would not be shown. Now, the chapters tab is always shown for episodes that have chapters and a spinner will be displayed if the chapters are still loading at the point you visit the tab. Hopefully I will push a set of updates, including this fix, later today. Thanks.
