### ISSUE TITLE
Error on run flutter pub get - Flutter 2 dependency Issue

### ISSUE THREAD

**Issue by sinhpn92** [amugofjava/anytime_podcast_player#39]
**Describe the bug**
I have got this error on run `flutter pub get`:
`pub get failed (1; So, because anytime depends on both podcast_search from git and intl 0.17.0, version solving failed.)`

This my flutter doctor:
```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2 20D64 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
```

What's wrong there? Have anysuggest to fix this error?
Thank you so much!

**Comment by amugofjava** [comment]
Hi,

Yes, unfortunately Anytime isn't compatible with Flutter 2 just yet. Flutter 2 requires a bump in version of the `intl` package which in turn causes a number of dependency issues. There is one dependency I am waiting on and currently helping the author test in bringing it up to date. For now, to build Anytime from source you'll need to do it against 1.22.6.

**Comment by erdemyerebasmaz** [comment]
@sinhpn92 You can add
```
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```
to `pubspec.yaml` as a workaround.

**Comment by amugofjava** [comment]
I have pushed a `flutter2-migration` branch that contains a working version migrated to Flutter 2 - if you want to try it out before I complete and merge to master.

**Comment by amugofjava** [comment]
I have updated code and dependencies to work with Flutter 2.x and pushed to `master`.
