### ISSUE TITLE
Add support for importing/exporting subscriptions in OPML format

### ISSUE THREAD

**Issue by villiers-s** [amugofjava/anytime_podcast_player#45]
**Is your feature request related to a problem? Please describe.**
As a user wanting to migrate from a different app to Anytime, I would like to be able to import an OPML file of all my subscriptions that I exported from my previous app, so that I don't have to manually add all of them in Anytime.

Additionally (could be split into a separate feature request)
As a user, I want to be able to export the subscriptions I have in Anytime in OPML format so that I can easily migrate to a different app or if I want to share my subscription list or just have a backup of it.

**Describe the solution you'd like**
I would like to be able to import an OPML (standard format of a list of RSS feeds) of my podcast subscriptions into Anytime.

Additionally I would also like to be able to export my subscriptions in an OPML format.

**Describe alternatives you've considered**
Adding my 30+ subscriptions manually.

**Additional context**
_N/A_

**Comment by amugofjava** [comment]
Hi @villiers-s,

I have been looking into the OPML format recently and plan to work on this feature next. I have a couple of bug fixes in the queue first then I should be able to work on this.

**Comment by anatolyraklyar** [comment]
Hi amugofjava, when do you think this would be released?

**Comment by amugofjava** [comment]
Hi @anatolyraklyar - I am aiming to add OPML support by the end of May.

**Comment by amugofjava** [comment]
Due to unforeseen circumstances I am behind in implementing this feature. Work is in progress though and I hope to push a working version very soon.

**Comment by amugofjava** [comment]
Hi @villiers-s & @anatolyraklyar,

I have pushed an initial working OPML import function to a separate branch. This is not complete (and export needs to be done), but any early feedback would be really appreciated. Please let me know if this import works for you. Thanks.

https://github.com/amugofjava/anytime_podcast_player/tree/feature/opml

**Comment by anatolyraklyar** [comment]
Thanks Ben,

I'm having issues with my desktop but will let you know if it looks wrong
when I get a chance.  When do you think you're going to release
filter/categories?

**Comment by amugofjava** [comment]
Feature pushed to `master`.
