### ISSUE TITLE
"Search provider" in settings jumps back to "iTunes" when changing other settings

### ISSUE THREAD

**Issue by villiers-s** [amugofjava/anytime_podcast_player#46]
**Describe the bug**
After I set the "Search provider" to "PodcastIndex" and I make another change in the settings, it sets the seach provider back to "iTunes"

**To Reproduce**
1. Go to Settings
2. Set the Search provider to "PodcastIndex"
3. Make any other settings change
4. The search provider is now set as "iTunes" again

**Expected behavior**
The search provider setting must not change when changing other settings.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 4a (5G)
 - OS: Android 11

**Additional context**
N/A

**Comment by amugofjava** [comment]
Thanks for reporting this. I will include this in the fixes I am currently working on.

**Comment by amugofjava** [comment]
This has been fixed.
