### ISSUE TITLE
Podcast Artist Page

### ISSUE THREAD

**Issue by ghost** [amugofjava/anytime_podcast_player#47]
When the podcast description is long, showing a button can provide a better experience.

![photo_2021-05-05_02-22-34](https://user-images.githubusercontent.com/61169988/117081956-ace77580-ad49-11eb-99cf-01bb88c36630.png)

**Comment by amugofjava** [comment]
That's a good idea @bakinazik - I'll look into that. Thanks.

**Comment by GouravShDev** [comment]
I'll like to work on this feature. If you are not working on it @amugofjava .

**Comment by amugofjava** [comment]
Hi @GouravShDev,

I have very recently added this feature; however, as you can see from the short clip below the toggle between short and long description is very abrupt - there is no animation. It needs enhancing so it animates in and out smoothly like the ExpansionTile widget does. Would adding this animation be something you would be interested in working on?

[device-2023-02-17-190543.webm](https://user-images.githubusercontent.com/5526902/219764805-186e7a29-7c32-463f-9484-afd2a63ccb54.webm)

**Comment by GouravShDev** [comment]
@amugofjava yeah definitely.
