### ISSUE TITLE
Distribute APK with release

### ISSUE THREAD

**Issue by AbelLykens** [amugofjava/anytime_podcast_player#59]
**Is your feature request related to a problem? Please describe.**
I don't have Play Store -- Can't use AnyTime

**Describe the solution you'd like**
I'd like to be able to download APKs

**Describe alternatives you've considered**
Using those sites that get the APKs, but I don't like having to trust middlemen.

**Additional context**
Breez distributes APKs with each release (on the github release page), that works well.

**Comment by amugofjava** [comment]
Hi @AbelLykens,

The latest Beta has been added to the release section.
