### ISSUE TITLE
[iOS] Add manual RSS feed shows error

### ISSUE THREAD

**Issue by Chralu** [amugofjava/anytime_podcast_player#68]
**Describe the bug**
On an iOS device, **Add Rss Feed** popup show error `No Material widget found. TextField widgets require a Material widget ancestor`.

**To Reproduce**
1. Go on "Library" tab
2. Click on the action button on the top-right corner
3. Select "Add RSS Feed"
4. The requested popup shows empty, and the following error is logged :

```
The following assertion was thrown building TextField(controller: TextEditingController#0419f(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))), decoration: InputDecoration(hintText: "https://"), dirty, dependencies: [MediaQuery, UnmanagedRestorationScope], state: _TextFieldState#fb112):
No Material widget found.

TextField widgets require a Material widget ancestor.
In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's material library, that material is represented by the Material widget. It is the Material widget that renders ink splashes, for instance. Because of this, many material library widgets require that there be a Material widget in the tree above them.
```

**Screenshots**
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-22 at 10 10 50](https://user-images.githubusercontent.com/375723/150632499-143f0369-eeb9-4f12-b131-a42178d3ed4b.png)

**Smartphone (please complete the following information):**
 - Device: iPhone13 Pro Max simulator
 - OS: iOS 15.2

**Comment by amugofjava** [comment]
Thanks @Chralu for raising this. How did I miss this one?!

**Comment by amugofjava** [comment]
Hi @Chralu,

This should be fixed in the current please. Please can you let me know if this now works correctly for you. Thanks.

**Comment by Chralu** [comment]
Hi,

this issue seems to be back (on `master` branch).
