### ISSUE TITLE
OPML Import hangs on a certain podcast

### ISSUE THREAD

**Issue by tomtom** [amugofjava/anytime_podcast_player#71]
**Describe the bug**
When I import an OPML file, the app consistently hangs when trying to download "https://www.geierb.de/trishaspodcasts/FM4-Charts/podcast.xml"

**Smartphone (please complete the following information):**
 - Device: Samsung a52
 - OS: Android 12

**Additional context**
I think it would be a good idea to download podcasts with a timeout. If the app cannot download/process a podcast, the problem should be limited to the problematic podcast. The way it is now the only option is to abort importing the OPML.

**Comment by amugofjava** [comment]
Hi @tomtom,

Would you mind sharing your OPML file so I can test & watch the import locally?

Thanks,

Ben.

**Comment by amugofjava** [comment]
Hi @tomtom,

I have tried this issue again today and successfully imported an OPML file containing the FM4 Charts podcast. If this is still an issue for you, please can you send me an example OPML to try.

**Comment by tomtom** [comment]
I switched to podcast addict for now, which is why I cannot check if 
this is still an issue. Thank you very much for revisiting this issue.
