### ISSUE TITLE
Cannot play a redirected episode 

### ISSUE THREAD

**Issue by kingonly** [amugofjava/anytime_podcast_player#77]
**Describe the bug**
It seems that Anytime cannot play op3 redirected episodes. Maybe an issue with the enclosure URL?

**To Reproduce**
1. Go to 'Curry and The Keeper' podcast 
2. Click on the play button of episode 22
3. Episode isn't playing 

**Expected behavior**
Should play like other episodes

**Screenshots**
![Screenshot_2022-09-29-06-54-27-44_5a6daf00ebe96535dfcd2244bec324cc](https://user-images.githubusercontent.com/31890660/192935797-959c32fb-91f4-495f-be5f-ab31450bdc31.jpg)

**Smartphone**
 - OnePlus 8T
 - Android 11

**Additional context**
I was told this specific episode is using a redirected enclosure URL.

**Comment by ademar111190** [comment]
I found the problem, there is a space on the URL: `<enclosure url="https://op3.dev/e/mp3s.nashownotes.com/CATK-22-2022-09-28-Final.mp3 " type="audio/mpeg" length="59004805"/>` http://feed.nashownotes.com/catkrss.xml

I'll trim the URL before trying to download it to fix this bug.
