### ISSUE TITLE
Clear text button in search UI should restore user keyboard

### ISSUE THREAD

**Issue by IvanVnucec** [amugofjava/anytime_podcast_player#80]
To recreate the issue to the following:
1. Open app
2. Click on the Search icon (top right)
3. Type some string into search bar
4. Click the back button **on your phone** (not on the screen)
5. Click on the Clear button (X symbol)

The app is clearing the search query and restoring focus as needed but the keyboard should pop up for user to input its search query again.

To implement this append the `SystemChannels.textInput.invokeMethod('TextInput.show');` to the `lib/ui/search/search_bar.dart`:
```dart
onPressed: () {
  _searchController.clear();
  FocusScope.of(context).requestFocus(FocusNode());
  SystemChannels.textInput.invokeMethod('TextInput.show');
}),
```

**Comment by amugofjava** [comment]
Hi,

Thanks for raising this issue and providing the solution. I will incorporate this into the next release.

**Comment by IvanVnucec** [comment]
Hey, no problem. Thanks for being open source.

**Comment by amugofjava** [comment]
This has been added and pushed to `master`. Thank you.
