### ISSUE TITLE
OPML Import - cannot select input file on iOS

### ISSUE THREAD

**Issue by amugofjava** [amugofjava/anytime_podcast_player#82]
**Describe the bug**
When attempting to select an OPML file on the device or iCloud, any OPML files are greyed out and not selectable.

**To Reproduce**
1. Got to settings and select Import OPML.
2. Use the file manager to locate an OPML file.
3. The file will be greyed out and cannot be selected.

**Expected behavior**
OPML files should be selectable for import.

**Screenshots**
![Screenshot 2023-02-02 at 16 18 29](https://user-images.githubusercontent.com/5526902/216382513-06226bba-2c8a-4532-94f1-15bb9b393113.png)

**Smartphone (please complete the following information):**
 - iPhone 7
 - iOS 15.7.2

**Additional context**
There is an additional problem with export. If you select Export OPML and then close the popup share panel you are left with a blank screen. You have to kill and restart Anytime to get out of it.

**Comment by Chralu** [comment]
Hi @amugofjava ,

this iOS issue seems directly related to file_picker : https://github.com/miguelpruivo/flutter_file_picker/issues/1148
