### ISSUE TITLE
Download tab does not automatically refresh on completion of episode download

### ISSUE THREAD

**Issue by amugofjava** [amugofjava/anytime_podcast_player#86]
**Describe the bug**
Episodes can be downloaded in the background. If a user switches to the download tab and a background download completes, the downloaded episode does not automatically appear in the list. The user has to switch to another tab and then back to the download tab to see the newly downloaded episode.

**To Reproduce**
1. Start an episode download.
2. Switch to the download tab and wait for the download to complete.
3. The downloaded episode does not appear on the list.
4. Switch to the library or discovery tab and then back to the downloads tab. The episode now appears.

**Expected behavior**
As a download completes, the newly downloaded episode should appear in the list. A download should not result in a complete redraw of the download screen; the episode should be added to the list without affecting the users' current scroll position.

**Comment by GouravShDev** [comment]
I would like to work on this issue. @amugofjava

**Comment by amugofjava** [comment]
Thank you @GouravShDev, please go ahead.
