### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [amugofjava/anytime_podcast_player#89]
Please add support Themed Icon on Android.

**Comment by amugofjava** [comment]
Hi @xmha97,

I have added a monochrome icon and tested on an Android 13 emulator. I don't have a physical Android 13 device. Would you be able to try this out? Thanks.

**Comment by xmha97** [comment]
Yes, please release a new version.

**Comment by amugofjava** [comment]
I have pushed a new release to the Beta channel.
